import type { FeedStatus, SpaceWeather } from '../lib/data/live';
import type { CloseApproach } from '../lib/data/types';
import { formatDistanceInline } from '../lib/format';
import { AU_KM } from '../lib/astro/constants';
import { Sheet } from './Sheet';

/**
 * The data log.
 *
 * Where the numbers come from, how old they are, and what they cannot do. This exists
 * because an app that mixes computed ephemerides, live feeds, baked catalogue constants
 * and openly simulated scenery owes the user one place that lays the whole arrangement
 * out.
 */

const AGE = (iso?: string): string => {
  if (!iso) return '';
  const ms = Date.now() - new Date(iso).getTime();
  if (!Number.isFinite(ms)) return '';
  const min = ms / 60000;
  if (min < 1) return 'seconds ago';
  if (min < 90) return `${Math.round(min)} min ago`;
  return `${(min / 60).toFixed(1)} h ago`;
};

export function DataSheet(props: {
  feeds: FeedStatus[];
  weather: SpaceWeather | null;
  approaches: CloseApproach[];
  onClose: () => void;
  onPickApproach: (a: CloseApproach) => void;
}) {
  return (
    <Sheet title="DATA" note="SOURCES · EPOCHS · LIMITS" onClose={props.onClose}>
      <div class="prose" style={{ borderBottom: '1px solid var(--hairline)' }}>
        <p>
          <strong>Planets, the Moon and the Lagrange points are computed here</strong>, from published
          analytical theories — no network needed, valid for any instant the scrubber reaches.
        </p>
        <p>
          <strong>Satellites, probe vectors and close approaches come from live feeds</strong> through this
          app’s own Worker, which holds any API credentials server-side. When a feed is down the
          app keeps working and says so.
        </p>
        <p>
          <strong>Everything marked SIMULATED is generated by this app</strong> and corresponds to no real
          object. It sits in real orbital regions so the mechanics are right, but nothing in the sky
          matches it.
        </p>
      </div>

      <div class="sheet-head" style={{ borderTop: '1px solid var(--hairline)' }}>
        <span class="note">FEEDS</span>
      </div>

      {props.feeds.length === 0 ? (
        <div class="prose">No live feeds have been contacted yet.</div>
      ) : (
        props.feeds.map((f) => (
          <div class="feed" key={f.id}>
            <span class={`dot ${f.ok ? 'ok' : 'bad'}`} style={{ marginTop: 5 }} />
            <span style={{ minWidth: 0, flex: 1 }}>
              <div class="fname">
                {f.label} <span style={{ color: f.ok ? 'var(--good)' : 'var(--bad)' }}>{f.ok ? 'ONLINE' : 'UNAVAILABLE'}</span>
              </div>
              <div class="fdetail">{f.detail}{f.fetchedAt ? ` · fetched ${AGE(f.fetchedAt)}` : ''}</div>
              {f.attribution ? <div class="fsrc">{f.attribution}</div> : null}
              {f.limitations ? <div class="fsrc" style={{ color: 'var(--faint)' }}>Limits: {f.limitations}</div> : null}
            </span>
          </div>
        ))
      )}

      {props.weather ? (
        <>
          <div class="sheet-head"><span class="note">GEOMAGNETIC ACTIVITY</span></div>
          <div class="readout" style={{ borderBottom: '1px solid var(--hairline)' }}>
            <div class="cell">
              <div class="k">Planetary K-index</div>
              <div class="v">{props.weather.kp.toFixed(2)}</div>
              <div class="aside">{props.weather.timeTag.replace('T', ' ').slice(0, 16)}Z</div>
            </div>
            <div class="cell">
              <div class="k">Storm level</div>
              <div class="v" style={{ color: props.weather.stormLevel === 'QUIET' ? 'var(--good)' : 'var(--accent)' }}>
                {props.weather.stormLevel}
              </div>
              <div class="aside">NOAA G-scale</div>
            </div>
          </div>
        </>
      ) : null}

      {props.approaches.length > 0 ? (
        <>
          <div class="sheet-head">
            <span class="note">UPCOMING CLOSE APPROACHES · JPL</span>
          </div>
          {props.approaches.slice(0, 20).map((a) => (
            <button class="result" key={`${a.designation}-${a.jd}`} onClick={() => props.onPickApproach(a)}>
              <span style={{ minWidth: 0 }}>
                <div class="rname">{a.fullName || a.designation}</div>
                <div class="rsub">
                  {new Date((a.jd - 2440587.5) * 86400000).toISOString().slice(0, 16).replace('T', ' ')}Z
                  {a.diameterM ? ` · ${Math.round(a.diameterM[0])}–${Math.round(a.diameterM[1])} m` : ''}
                </div>
              </span>
              <span class="rmeta">
                <div class="rsub" style={{ margin: 0, color: a.distAu < 0.005 ? 'var(--accent)' : 'var(--dim)' }}>
                  {formatDistanceInline(a.distAu * AU_KM)}
                </div>
                <div class="rsub">{a.vRelKmS.toFixed(1)} km/s</div>
              </span>
            </button>
          ))}
          <div class="prose">
            <p>
              These distances are JPL’s own numerically integrated solutions. This app draws orbits
              with a single unperturbed conic, which is good enough to see the shape of an orbit and
              not good enough to predict an approach — where the two disagree, JPL is right.
            </p>
          </div>
        </>
      ) : null}

      <div class="sheet-head"><span class="note">KNOWN LIMITATIONS</span></div>
      <div class="prose">
        <p>
          <strong>Planetary positions</strong> use secular Keplerian elements, accurate to arcminutes
          across 1800–2050 and degrading outside it. Pluto is the worst of the set.
        </p>
        <p>
          <strong>Satellite propagation</strong> implements the near-Earth branch of SGP4 only. Objects
          with a period of 225 minutes or more — geostationary, Molniya, GNSS — need the deep-space
          SDP4 half, which this build does not have, so they are refused rather than propagated
          badly.
        </p>
        <p>
          <strong>Small-body positions</strong> come from a single osculating conic with no planetary
          perturbations. Orbit shapes are right; the position along the orbit drifts from reality
          over years.
        </p>
        <p>
          <strong>The background star field</strong> is decoration. Twenty named bright stars are at
          their real catalogue positions; the faint scatter behind them carries no data at all.
        </p>
      </div>
    </Sheet>
  );
}
