import { useState } from 'preact/hooks';
import { AU_KM } from '../lib/astro/constants';
import { formatLightTime } from '../lib/astro/time';
import {
  distanceAside,
  formatDistance,
  formatDuration,
  formatSpeed,
  speedAside,
} from '../lib/format';
import type { ObjectReadout, Telemetry } from '../lib/render/engine';
import type { Provenance } from '../lib/data/types';
import { IconChase, IconTrack, IconTrajectory } from './icons';

/**
 * The object panel.
 *
 * Compact by default: a dense readout grid, one row of actions, and the provenance strip.
 * Facts and the full source record are behind MORE, because the panel's job is to keep you
 * flying, not to be read.
 *
 * The provenance strip is not optional and never collapses to nothing — whatever else is
 * on screen, the tier badge is there saying whether this object is computed, live,
 * catalogued or simulated.
 */

function Cell(props: { k: string; v: string; unit?: string; aside?: string | null }) {
  return (
    <div class="cell">
      <div class="k">{props.k}</div>
      <div class="v">
        {props.v}
        {props.unit ? <small>{props.unit}</small> : null}
      </div>
      {props.aside ? <div class="aside">{props.aside}</div> : null}
    </div>
  );
}

/** Display names for object kinds. The raw union members are not English. */
const KIND_LABEL: Record<string, string> = {
  star: 'STAR',
  planet: 'PLANET',
  dwarf: 'DWARF PLANET',
  moon: 'MOON',
  spacecraft: 'SPACECRAFT',
  satellite: 'SATELLITE',
  asteroid: 'ASTEROID',
  comet: 'COMET',
  interstellar: 'INTERSTELLAR OBJECT',
  lagrange: 'LAGRANGE POINT',
  debris: 'DEBRIS',
};

const TIER_LABEL: Record<Provenance['tier'], string> = {
  computed: 'COMPUTED',
  live: 'LIVE',
  catalog: 'CATALOG',
  simulated: 'SIMULATED',
};

export function ProvenanceStrip(props: { provenance: Provenance; expanded: boolean }) {
  const p = props.provenance;
  return (
    <div class="prov">
      <span class={`tier ${p.tier}`}>{TIER_LABEL[p.tier]}</span>
      {p.tier === 'simulated'
        ? 'This object does not exist. It is generated by this app.'
        : p.source}
      {props.expanded ? (
        <dl>
          {p.epoch ? <><dt>Epoch</dt><dd>{p.epoch.replace('T', ' ').slice(0, 19)}Z</dd></> : null}
          <dt>Update</dt><dd>{p.cadence}</dd>
          <dt>Accuracy</dt><dd>{p.accuracy}</dd>
          <dt>Limits</dt><dd>{p.limitations}</dd>
          {p.sourceUrl ? (
            <>
              <dt>Source</dt>
              <dd>
                <a href={p.sourceUrl} target="_blank" rel="noreferrer noopener" style={{ color: 'var(--cyan)' }}>
                  {p.sourceUrl.replace(/^https?:\/\//, '')}
                </a>
              </dd>
            </>
          ) : null}
        </dl>
      ) : null}
    </div>
  );
}

export function ObjectPanel(props: {
  readout: ObjectReadout;
  telemetry: Telemetry;
  onClose: () => void;
  onTrack: () => void;
  onChase: () => void;
  onToggleTrajectory: () => void;
  onTimeTravel: () => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const r = props.readout;
  const t = props.telemetry;

  const tracked = t.trackedId === r.id;
  const earthDist = formatDistance(r.distanceFromEarthKm);
  const sunDist = formatDistance(r.distanceFromSunKm);

  // An unplaced object has no position, so every quantity derived from one is meaningless.
  // Showing "0 m" or a distance measured from the origin would be worse than showing
  // nothing — it would look like an answer. The orbital elements below are still real.
  const unknown = r.unplaced;

  // Which speed is meaningful depends on what the thing is orbiting. For the ISS,
  // "7.66 km/s" (around the Earth) is the number people expect; for Mars it is the
  // heliocentric speed.
  const showLocalSpeed = r.parentName !== null && r.parentName !== 'SUN' && r.localSpeedKmS > 0.01;

  return (
    <div class="objpanel">
      <div class="head">
        <span class="swatch" style={{ background: r.color }} />
        <div class="titles">
          <div class="kicker">OBJECT · {KIND_LABEL[r.kind] ?? r.kind.toUpperCase()}</div>
          <h2>{r.name}</h2>
          {r.subtitle ? <div class="sub">{r.subtitle}</div> : null}
        </div>
        <button class="close-x" onClick={props.onClose} aria-label="Close object panel">×</button>
      </div>

      {r.unplaced ? (
        <div class="simbanner" style={{ color: 'var(--accent)', borderColor: 'rgba(255,176,0,.3)', background: 'rgba(255,176,0,.08)' }}>
          POSITION NOT AVAILABLE — ORBIT SHOWN, BODY NOT PLACED
        </div>
      ) : null}
      {r.phaseSynthetic && !r.unplaced ? (
        <div
          class="simbanner"
          style={{ color: 'var(--cyan)', borderColor: 'rgba(111,211,255,.3)', background: 'rgba(111,211,255,.08)' }}
        >
          ORBIT IS REAL — POSITION ALONG IT IS NOT FITTED
        </div>
      ) : null}
      {r.provenance.tier === 'simulated' ? (
        <div class="simbanner">SIMULATED OBJECT — NOT A REAL BODY</div>
      ) : null}

      <div class="readout">
        {/* Earth is the reference body for "distance from Earth" and "signal delay", so
            for Earth itself both cells would read zero. Say what is actually true
            instead. */}
        {r.id === 'earth' ? (
          <Cell k="Observer frame" v="REFERENCE" aside="all distances are measured from here" />
        ) : (
          <Cell
            k="Distance from Earth"
            v={unknown ? '—' : earthDist.value}
            {...(unknown ? {} : { unit: earthDist.unit })}
            aside={unknown ? 'position not known offline' : distanceAside(r.distanceFromEarthKm)}
          />
        )}
        <Cell
          k="Distance from Sun"
          v={unknown ? '—' : sunDist.value}
          {...(unknown ? {} : { unit: sunDist.unit })}
          aside={unknown ? 'position not known offline' : `${(r.distanceFromSunKm / AU_KM).toFixed(4)} AU`}
        />
        <Cell
          k={showLocalSpeed ? `Speed rel. ${r.parentName}` : 'Velocity'}
          v={unknown ? '—' : formatSpeed(showLocalSpeed ? r.localSpeedKmS : r.speedKmS)}
          aside={unknown ? 'requires a position' : speedAside(showLocalSpeed ? r.localSpeedKmS : r.speedKmS)}
        />
        {r.id === 'earth' ? (
          <Cell k="Axial tilt" v="23.44°" aside="the reason there are seasons" />
        ) : (
          <Cell
            k="Signal delay"
            v={unknown ? '—' : formatLightTime(r.signalDelaySec)}
            aside={unknown ? 'requires a position' : `round trip ${formatLightTime(r.signalDelaySec * 2)}`}
          />
        )}
        {r.altitudeKm !== null && Number.isFinite(r.altitudeKm) ? (
          <Cell k={`Altitude over ${r.parentName ?? ''}`} v={formatDistance(r.altitudeKm).value} unit={formatDistance(r.altitudeKm).unit} />
        ) : null}
        {r.orbitalPeriodDays ? (
          <Cell k="Orbital period" v={formatDuration(r.orbitalPeriodDays)} />
        ) : null}
        {unknown && r.periapsisKm && r.apoapsisKm ? (
          <Cell
            k="Orbit spans"
            v={`${(r.periapsisKm / AU_KM).toFixed(2)}–${(r.apoapsisKm / AU_KM).toFixed(2)}`}
            unit="AU"
            aside="from the published elements"
          />
        ) : null}
        {r.eccentricity !== null ? (
          <Cell
            k="Eccentricity"
            v={r.eccentricity.toFixed(4)}
            aside={r.eccentricity >= 1 ? 'hyperbolic — unbound' : r.eccentricity > 0.3 ? 'strongly elliptical' : 'near-circular'}
          />
        ) : null}
        {r.inclinationDeg !== null ? (
          <Cell
            k="Inclination"
            v={`${r.inclinationDeg.toFixed(2)}°`}
            aside={r.inclinationDeg > 90 ? 'retrograde' : 'prograde'}
          />
        ) : null}
        <div class="cell" style={{ gridColumn: '1 / -1', borderRight: 'none' }}>
          <div class="k">Status</div>
          <div class="v" style={{ fontSize: 12, color: r.status?.includes('SIMULATED') ? 'var(--sim)' : 'var(--text)' }}>
            {r.status ?? 'TRACKED'}
          </div>
        </div>
      </div>

      <div class="actions">
        <button class="action" aria-pressed={tracked} onClick={props.onTrack} disabled={r.unplaced}>
          <IconTrack /> {tracked ? 'TRACKING' : 'TRACK'}
        </button>
        <button
          class="action chase"
          aria-pressed={t.chase && tracked}
          onClick={props.onChase}
          disabled={r.unplaced}
        >
          <IconChase /> CHASE
        </button>
        <button class="action" aria-pressed={t.layers.trajectory} onClick={props.onToggleTrajectory}>
          <IconTrajectory /> TRAJECTORY
        </button>
        <button class="action" onClick={props.onTimeTravel}>TIME TRAVEL</button>
        <button class="action" aria-pressed={expanded} onClick={() => setExpanded((v) => !v)}>
          {expanded ? 'LESS' : 'MORE'}
        </button>
      </div>

      {expanded ? (
        <>
          {r.facts.length > 0 ? (
            <div class="facts">
              {r.facts.map((f) => (
                <div class="fact" key={f.label}>
                  <span class="fk">{f.label}</span>
                  <span class="fv">{f.value}</span>
                </div>
              ))}
            </div>
          ) : null}

          {t.neighbours.length > 0 ? (
            <div class="facts" style={{ borderTop: '1px solid var(--hairline)' }}>
              <div class="fact">
                <span class="fk" style={{ color: 'var(--dim)' }}>Nearest objects</span>
                <span class="fv" />
              </div>
              {t.neighbours.map((n) => (
                <div class="fact" key={n.id}>
                  <span class="fk" style={{ color: n.color }}>{n.name}</span>
                  <span class="fv" style={{ fontFamily: 'var(--mono)', fontSize: 11 }}>
                    {n.km > 0.01 * AU_KM
                      ? `${(n.km / AU_KM).toFixed(3)} AU`
                      : `${Math.round(n.km).toLocaleString('en-US')} km`}
                  </span>
                </div>
              ))}
            </div>
          ) : null}
        </>
      ) : null}

      <ProvenanceStrip provenance={r.provenance} expanded={expanded} />
    </div>
  );
}
