import { AU_KM, DEG, GM, RADIUS } from '../astro/constants';
import { elementsFromDegrees, wrap2Pi, type Elements } from '../astro/kepler';
import { PLANET_IDS, planetElements, type PlanetId } from '../astro/planets';
import { buildMoons } from './moons';
import { buildSmallBodies } from './smallbodies';
import { buildSpacecraft } from './spacecraft';
import type { Provenance, SpaceObject } from './types';

/**
 * The built-in catalogue.
 *
 * Everything here is either computed from a published theory or copied from a published
 * source, and each entry says which. Nothing in this file is invented. Where a real
 * object's orbit shape is well known but its phase along that orbit is not, the entry is
 * marked `phaseUnknown` and the app draws the path without claiming to place the body —
 * see `elementsUnphased` below.
 */

// ---------------------------------------------------------------------------
// Provenance records, written once and shared.
// ---------------------------------------------------------------------------

const P_PLANET: Provenance = {
  tier: 'computed',
  source: 'E. M. Standish, "Keplerian Elements for Approximate Positions of the Major Planets", JPL Solar System Dynamics',
  sourceUrl: 'https://ssd.jpl.nasa.gov/planets/approx_pos.html',
  cadence: 'Analytical — no refresh. Valid for any instant.',
  accuracy: 'Sub-arcminute heliocentric longitude for the inner planets, 1800–2050. A few arcminutes for the outer planets; worst for Pluto.',
  limitations: 'Secular rates only: no planetary perturbations, so error grows outside 1800–2050. Not for navigation or occultation prediction.',
};

const P_MOON: Provenance = {
  tier: 'computed',
  source: 'Jean Meeus, Astronomical Algorithms (2nd ed.), ch. 47 — ELP-2000/82 truncation',
  cadence: 'Analytical — no refresh.',
  accuracy: '~10 arcseconds in longitude, a few km in distance, near the present epoch.',
  limitations: 'The 51 largest periodic terms of a much longer series. Degrades slowly away from the present century.',
};

const P_SUN: Provenance = {
  tier: 'computed',
  source: 'Definition — the origin of the heliocentric frame used throughout this app.',
  cadence: 'Fixed by construction.',
  accuracy: 'Exact by definition. The Sun actually wobbles about the Solar System barycentre by up to ~1.3 solar radii; that motion is not modelled.',
  limitations: 'Treated as fixed at the origin. Radius and rotation are IAU mean values.',
};

const P_MAJOR_MOON: Provenance = {
  tier: 'catalog',
  source: 'IAU/JPL published mean orbital elements for the major planetary satellites',
  sourceUrl: 'https://ssd.jpl.nasa.gov/sats/elem/',
  cadence: 'Static — baked into the build.',
  accuracy: 'Mean elements. Position along the orbit is good to a few tenths of a degree over years, not arcseconds.',
  limitations: 'No mutual perturbations, no precession of the node beyond the mean rate. Fine for showing where a moon is in its orbit; not for eclipse timing.',
};

const P_SMALL_BODY: Provenance = {
  tier: 'catalog',
  source: 'Published osculating elements (JPL Small-Body Database)',
  sourceUrl: 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html',
  cadence: 'Static — baked into the build. Live elements are fetched when the network allows.',
  accuracy: 'Orbit shape is good. Position along the orbit is approximate and degrades away from the stated epoch.',
  limitations: 'Single osculating conic: no planetary perturbations and no non-gravitational forces. Close-approach geometry from this model is indicative only.',
};

const P_PROBE_RADIANT: Provenance = {
  tier: 'catalog',
  source: 'Published mission distance, heliocentric speed and escape direction (NASA/JPL mission pages)',
  sourceUrl: 'https://voyager.jpl.nasa.gov/mission/status/',
  cadence: 'Static — baked into the build. Replaced by JPL Horizons vectors when reachable.',
  accuracy: 'Distance to roughly ±1 AU, direction to roughly ±1°. Enough to show where the probe is; not an ephemeris.',
  limitations: 'Straight-line model. Valid because solar gravity at >100 AU changes the speed by centimetres per second per year — but it is a model, not a trajectory solution.',
};

const P_LAGRANGE: Provenance = {
  tier: 'computed',
  source: 'Computed from the Earth ephemeris — the collinear Lagrange points of the Sun–Earth system',
  cadence: 'Analytical — follows the Earth.',
  accuracy: 'The libration point itself is exact to the linearised distance (1.5 million km). The halo orbit drawn around it is a representative circle, not the real trajectory.',
  limitations: 'Spacecraft at L1/L2 fly halo or Lissajous orbits hundreds of thousands of km wide. This shows the point and an indicative halo, not the operational trajectory.',
};

const P_SIM: Provenance = {
  tier: 'simulated',
  source: 'Generated by SPACE RADAR. Not a real object.',
  cadence: 'Regenerated from a fixed seed on every load.',
  accuracy: 'Not applicable — nothing here corresponds to a catalogued body.',
  limitations: 'Statistically representative of a real population, individually fictitious. Never use these for anything.',
};

export const PROVENANCE = {
  planet: P_PLANET,
  moon: P_MOON,
  sun: P_SUN,
  majorMoon: P_MAJOR_MOON,
  smallBody: P_SMALL_BODY,
  probe: P_PROBE_RADIANT,
  lagrange: P_LAGRANGE,
  simulated: P_SIM,
} as const;

// ---------------------------------------------------------------------------
// Element helpers
// ---------------------------------------------------------------------------

/** Elements from the AU/degree form catalogues publish, phased by time of perihelion. */
function heliocentric(opts: {
  aAu: number; e: number; iDeg: number; omDeg: number; wDeg: number;
  /** Julian Date of perihelion passage. */
  tp: number;
}): Elements {
  const a = opts.aAu * AU_KM;
  // M = n(t − Tp); at the epoch we choose (Tp itself) the mean anomaly is zero, so store
  // the elements with epoch = Tp and m0 = 0. Works for closed and open orbits alike.
  return {
    a,
    e: opts.e,
    i: opts.iDeg * DEG,
    om: opts.omDeg * DEG,
    w: opts.wDeg * DEG,
    m0: 0,
    epoch: opts.tp,
    mu: GM.sun,
  };
}

/** A conic whose shape is published but whose phase is not known offline. */
function unphased(opts: { aAu: number; e: number; iDeg: number; omDeg: number; wDeg: number }): Elements {
  return heliocentric({ ...opts, tp: 2451545.0 });
}

/** Elements for a satellite of a planet, given in km and degrees. */
function satellite(opts: {
  aKm: number; e: number; iDeg: number; omDeg: number; wDeg: number; m0Deg: number;
  epoch: number; mu: number;
}): Elements {
  return elementsFromDegrees(opts);
}

const jdOf = (iso: string): number => new Date(iso).getTime() / 86400000 + 2440587.5;

/**
 * Radius of the sphere of influence, km: r = a·(m/M)^(2/5) (Laplace).
 * `a` is the body's semi-major axis about its parent and m/M the mass ratio.
 */
function soi(aKm: number, muBody: number, muParent: number): number {
  return aKm * Math.pow(muBody / muParent, 0.4);
}

// ---------------------------------------------------------------------------
// Planets
// ---------------------------------------------------------------------------

const PLANET_META: Record<PlanetId, { name: string; color: string; weight: number; kind: 'planet' | 'dwarf'; facts: [string, string][] }> = {
  mercury: { name: 'MERCURY', color: '#a8a29a', weight: 0.7, kind: 'planet', facts: [['Day length', '58.6 Earth days'], ['Surface range', '−173 °C to 427 °C'], ['Moons', 'None']] },
  venus: { name: 'VENUS', color: '#d8c08a', weight: 0.75, kind: 'planet', facts: [['Surface pressure', '92 × Earth'], ['Rotation', 'Retrograde, 243 days'], ['Moons', 'None']] },
  earth: { name: 'EARTH', color: '#5c8fc4', weight: 1, kind: 'planet', facts: [['Moons', '1'], ['Atmosphere', '78% N₂, 21% O₂'], ['Known life', 'Yes']] },
  mars: { name: 'MARS', color: '#c1683f', weight: 0.9, kind: 'planet', facts: [['Moons', 'Phobos, Deimos'], ['Tallest volcano', 'Olympus Mons, 21.9 km'], ['Day length', '24 h 37 m']] },
  jupiter: { name: 'JUPITER', color: '#c9a882', weight: 0.9, kind: 'planet', facts: [['Moons', '95 confirmed'], ['Mass', '318 × Earth'], ['Great Red Spot', 'Wider than Earth']] },
  saturn: { name: 'SATURN', color: '#ddc99a', weight: 0.88, kind: 'planet', facts: [['Moons', '146 confirmed'], ['Ring span', '~282 000 km'], ['Mean density', 'Less than water']] },
  uranus: { name: 'URANUS', color: '#8fc4c9', weight: 0.7, kind: 'planet', facts: [['Axial tilt', '97.8° — rolls on its side'], ['Moons', '28 confirmed'], ['Visited by', 'Voyager 2, 1986']] },
  neptune: { name: 'NEPTUNE', color: '#5b7fc7', weight: 0.7, kind: 'planet', facts: [['Fastest winds', '~2 100 km/h'], ['Moons', '16 confirmed'], ['Visited by', 'Voyager 2, 1989']] },
  pluto: { name: 'PLUTO', color: '#b9a893', weight: 0.6, kind: 'dwarf', facts: [['Reclassified', '2006'], ['Moons', 'Charon + 4'], ['Visited by', 'New Horizons, 2015']] },
};

function planetObjects(): SpaceObject[] {
  return PLANET_IDS.map((id) => ({
    id,
    soiKm: soi(planetElements(id, 2451545.0).a, GM[id], GM.sun),
    name: PLANET_META[id].name,
    subtitle: PLANET_META[id].kind === 'dwarf' ? 'DWARF PLANET' : 'PLANET',
    kind: PLANET_META[id].kind,
    parent: 'sun',
    radiusKm: RADIUS[id],
    color: PLANET_META[id].color,
    weight: PLANET_META[id].weight,
    provenance: P_PLANET,
    ephemeris: { kind: 'planet', planet: id },
    tags: ['planet', 'solar-system'],
    facts: PLANET_META[id].facts.map(([label, value]) => ({ label, value })),
    status: 'TRACKED',
  }));
}

// ---------------------------------------------------------------------------
// Moons
// ---------------------------------------------------------------------------

function moonObjects(): SpaceObject[] {
  return [
    {
      id: 'moon',
      name: 'MOON',
      subtitle: 'EARTH I — LUNA',
      kind: 'moon',
      parent: 'earth',
      radiusKm: RADIUS.moon,
      color: '#c9c5bd',
      weight: 0.95,
      provenance: P_MOON,
      soiKm: soi(384_400, GM.moon, GM.earth),
      ephemeris: { kind: 'luna' },
      tags: ['moon', 'solar-system', 'earth'],
      aliases: ['luna'],
      facts: [
        { label: 'Mean distance', value: '384 400 km' },
        { label: 'Orbital period', value: '27.32 days (sidereal)' },
        { label: 'Receding at', value: '3.8 cm per year' },
        { label: 'Human visits', value: '6 landings, 1969–1972' },
      ],
      status: 'TRACKED',
    },
    // Every other natural satellite. Earth's Moon keeps its own analytic theory above;
    // the rest come from published mean elements in their planet's equatorial frame.
    ...buildMoons(),
  ];
}

// ---------------------------------------------------------------------------
// Spacecraft
// ---------------------------------------------------------------------------

/**
 * The interstellar probes.
 *
 * Each is published as a distance, a heliocentric speed and an escape direction, so that
 * is exactly how they are stored. The distances are stamped at a stated epoch and drift
 * linearly, which is what these trajectories actually do this far out.
 */
const PROBE_EPOCH = jdOf('2025-01-01T00:00:00Z');

const PROBES: ReadonlyArray<{
  id: string; name: string; subtitle: string; raDeg: number; decDeg: number;
  auAtEpoch: number; kmPerSec: number; color: string; weight: number; status: string;
  facts: [string, string][];
}> = [
  {
    id: 'voyager-1', name: 'VOYAGER 1', subtitle: 'NASA / JPL — LAUNCHED 1977-09-05',
    raDeg: 258.0, decDeg: 12.2, auAtEpoch: 165.9, kmPerSec: 16.99,
    color: '#f0b429', weight: 1, status: 'ACTIVE — INTERSTELLAR SPACE',
    facts: [['Heliopause crossing', '2012-08-25'], ['Transmitter power', '~22 W'], ['Heading toward', 'Ophiuchus'], ['Power remaining', 'RTG decays ~4 W/year']],
  },
  {
    id: 'voyager-2', name: 'VOYAGER 2', subtitle: 'NASA / JPL — LAUNCHED 1977-08-20',
    raDeg: 298.5, decDeg: -56.6, auAtEpoch: 138.3, kmPerSec: 15.37,
    color: '#f0b429', weight: 0.98, status: 'ACTIVE — INTERSTELLAR SPACE',
    facts: [['Heliopause crossing', '2018-11-05'], ['Only spacecraft to visit', 'Uranus and Neptune'], ['Heading toward', 'Pavo']],
  },
  {
    id: 'pioneer-10', name: 'PIONEER 10', subtitle: 'NASA / ARC — LAUNCHED 1972-03-02',
    raDeg: 76.0, decDeg: 25.9, auAtEpoch: 137.0, kmPerSec: 12.04,
    color: '#8c8478', weight: 0.7, status: 'CONTACT LOST 2003-01-23',
    facts: [['First to', 'Cross the asteroid belt and reach Jupiter'], ['Carries', 'The Pioneer plaque'], ['Heading toward', 'Aldebaran, ~2 million years out']],
  },
  {
    id: 'pioneer-11', name: 'PIONEER 11', subtitle: 'NASA / ARC — LAUNCHED 1973-04-06',
    raDeg: 287.0, decDeg: -8.9, auAtEpoch: 115.0, kmPerSec: 11.34,
    color: '#8c8478', weight: 0.65, status: 'CONTACT LOST 1995-11-24',
    facts: [['First to', 'Fly past Saturn'], ['Heading toward', 'Scutum'], ['Carries', 'The Pioneer plaque']],
  },
  {
    id: 'new-horizons', name: 'NEW HORIZONS', subtitle: 'NASA / APL — LAUNCHED 2006-01-19',
    raDeg: 293.4, decDeg: -20.5, auAtEpoch: 59.6, kmPerSec: 13.68,
    color: '#7fb2d9', weight: 0.9, status: 'ACTIVE — KUIPER BELT',
    facts: [['Pluto flyby', '2015-07-14'], ['Arrokoth flyby', '2019-01-01'], ['Fastest launch speed', '16.26 km/s from Earth'], ['Heading toward', 'Sagittarius']],
  },
];

/** Inner-system missions with published heliocentric orbits. */
const INNER_MISSIONS: SpaceObject[] = [
  {
    id: 'parker-solar-probe',
    name: 'PARKER SOLAR PROBE',
    subtitle: 'NASA / APL — LAUNCHED 2018-08-12',
    kind: 'spacecraft',
    parent: 'sun',
    color: '#ff7a45',
    weight: 0.95,
    provenance: {
      ...P_SMALL_BODY,
      source: 'Published final-orbit elements, Parker Solar Probe mission (NASA/APL)',
      accuracy: 'Orbit shape is the published post-2024 science orbit. Phase is approximate.',
      limitations: 'The real trajectory changed at each of seven Venus gravity assists; only the final orbit is modelled.',
    },
    // Final science orbit: perihelion 0.0459 AU, aphelion 0.73 AU, period ~88 days.
    ephemeris: {
      kind: 'elements',
      elements: heliocentric({ aAu: 0.388, e: 0.8823, iDeg: 3.4, omDeg: 178.1, wDeg: 270.0, tp: jdOf('2024-12-24T11:53:00Z') }),
    },
    tags: ['spacecraft', 'active'],
    status: 'ACTIVE — SOLAR ORBIT',
    facts: [
      { label: 'Closest approach', value: '6.16 million km from the Sun' },
      { label: 'Top speed', value: '~192 km/s — fastest human-made object' },
      { label: 'Heat shield', value: '1 370 °C on the front, 30 °C behind it' },
    ],
  },
  {
    id: 'jwst',
    name: 'JAMES WEBB SPACE TELESCOPE',
    subtitle: 'NASA / ESA / CSA — LAUNCHED 2021-12-25',
    kind: 'spacecraft',
    parent: 'earth',
    color: '#e0c060',
    weight: 0.95,
    provenance: P_LAGRANGE,
    ephemeris: { kind: 'lagrange', point: 'L2', haloKm: 832_000, haloPeriodDays: 178, phase: 0.2 },
    aliases: ['webb', 'jwst'],
    tags: ['spacecraft', 'active', 'telescope'],
    status: 'ACTIVE — SUN–EARTH L2 HALO',
    facts: [
      { label: 'Mirror', value: '6.5 m, 18 beryllium segments' },
      { label: 'Operating temperature', value: 'Below −223 °C' },
      { label: 'Distance from Earth', value: '~1.5 million km' },
      { label: 'Sunshield', value: 'Tennis-court sized, 5 layers' },
    ],
  },
  {
    id: 'soho',
    name: 'SOHO',
    subtitle: 'ESA / NASA — LAUNCHED 1995-12-02',
    kind: 'spacecraft',
    parent: 'earth',
    color: '#d9a441',
    weight: 0.7,
    provenance: P_LAGRANGE,
    ephemeris: { kind: 'lagrange', point: 'L1', haloKm: 666_000, haloPeriodDays: 180, phase: 1.7 },
    aliases: ['solar and heliospheric observatory'],
    tags: ['spacecraft', 'active', 'solar'],
    status: 'ACTIVE — SUN–EARTH L1 HALO',
    facts: [
      { label: 'Watches', value: 'The Sun, continuously, since 1996' },
      { label: 'Side effect', value: 'Has discovered over 5 000 comets' },
      { label: 'Warning time', value: 'Gives Earth ~1 hour of solar-storm notice' },
    ],
  },
  {
    id: 'gaia',
    name: 'GAIA',
    subtitle: 'ESA — LAUNCHED 2013-12-19',
    kind: 'spacecraft',
    parent: 'earth',
    color: '#9fb4c7',
    weight: 0.6,
    provenance: P_LAGRANGE,
    ephemeris: { kind: 'lagrange', point: 'L2', haloKm: 263_000, haloPeriodDays: 180, phase: 3.4 },
    tags: ['spacecraft', 'telescope'],
    status: 'RETIRED 2025-03 — L2 GRAVEYARD ORBIT',
    facts: [
      { label: 'Mapped', value: '~1.8 billion stars' },
      { label: 'Astrometric precision', value: 'Tens of microarcseconds' },
    ],
  },
];

function probeObjects(): SpaceObject[] {
  return PROBES.map((p) => ({
    id: p.id,
    name: p.name,
    subtitle: p.subtitle,
    kind: p.id.startsWith('voyager') || p.id.startsWith('pioneer') ? 'spacecraft' : 'spacecraft',
    parent: 'sun',
    color: p.color,
    weight: p.weight,
    provenance: P_PROBE_RADIANT,
    ephemeris: {
      kind: 'radiant',
      raDeg: p.raDeg,
      decDeg: p.decDeg,
      auAtEpoch: p.auAtEpoch,
      epoch: PROBE_EPOCH,
      kmPerSec: p.kmPerSec,
    },
    tags: ['spacecraft', 'deep-space'],
    status: p.status,
    facts: p.facts.map(([label, value]) => ({ label, value })),
  }));
}

// ---------------------------------------------------------------------------
// Small bodies
// ---------------------------------------------------------------------------

/**
 * Small bodies whose orbit *shape* is published and confidently known.
 *
 * `tp` — time of perihelion passage — is given only where it is well established. Without
 * it the phase along the orbit is unknown, the entry is marked `phaseUnknown`, and the app
 * draws the path but does not place the body. The live SBDB lookup fills those in.
 */
const SMALL_BODIES: ReadonlyArray<{
  id: string; name: string; subtitle: string; kind: 'asteroid' | 'comet' | 'interstellar' | 'dwarf';
  aAu: number; e: number; iDeg: number; omDeg: number; wDeg: number; tp?: string;
  radiusKm?: number; color: string; weight: number; status?: string; facts: [string, string][];
}> = [
  { id: 'ceres', name: 'CERES', subtitle: '(1) CERES — DWARF PLANET', kind: 'dwarf', aAu: 2.7658, e: 0.0785, iDeg: 10.587, omDeg: 80.3, wDeg: 73.6, radiusKm: 469.7, color: '#a49c90', weight: 0.6, facts: [['Share of belt mass', '~25%'], ['Visited by', 'Dawn, 2015–2018'], ['Bright spots', 'Sodium carbonate deposits']] },
  { id: 'vesta', name: 'VESTA', subtitle: '(4) VESTA — MAIN BELT', kind: 'asteroid', aAu: 2.3616, e: 0.0887, iDeg: 7.141, omDeg: 103.81, wDeg: 151.2, radiusKm: 262.7, color: '#b3a897', weight: 0.5, facts: [['Brightest asteroid', 'Occasionally naked-eye'], ['Rheasilvia crater', '505 km across']] },
  { id: 'pallas', name: 'PALLAS', subtitle: '(2) PALLAS — MAIN BELT', kind: 'asteroid', aAu: 2.771, e: 0.2299, iDeg: 34.84, omDeg: 172.92, wDeg: 310.05, radiusKm: 255.5, color: '#9a948e', weight: 0.45, facts: [['Inclination', '34.8° — steeply out of the ecliptic'], ['Discovered', '1802']] },
  { id: 'psyche', name: 'PSYCHE', subtitle: '(16) PSYCHE — MAIN BELT', kind: 'asteroid', aAu: 2.923, e: 0.134, iDeg: 3.1, omDeg: 150.0, wDeg: 229.6, radiusKm: 111, color: '#9d8f7d', weight: 0.5, facts: [['Composition', 'Largely metal'], ['NASA Psyche mission', 'Arrives 2029']] },
  { id: 'eros', name: 'EROS', subtitle: '(433) EROS — NEAR-EARTH', kind: 'asteroid', aAu: 1.4583, e: 0.2226, iDeg: 10.829, omDeg: 304.3, wDeg: 178.8, radiusKm: 8.4, color: '#c08f62', weight: 0.55, facts: [['First asteroid orbited', 'NEAR Shoemaker, 2000'], ['First asteroid landed on', '2001']] },
  { id: 'bennu', name: 'BENNU', subtitle: '(101955) BENNU — NEAR-EARTH', kind: 'asteroid', aAu: 1.1264, e: 0.2037, iDeg: 6.035, omDeg: 2.06, wDeg: 66.22, radiusKm: 0.245, color: '#8f8377', weight: 0.6, facts: [['Sample returned', 'OSIRIS-REx, 2023-09-24'], ['Surface', 'A loose rubble pile'], ['2182 impact odds', '~1 in 2 700']] },
  { id: 'ryugu', name: 'RYUGU', subtitle: '(162173) RYUGU — NEAR-EARTH', kind: 'asteroid', aAu: 1.1896, e: 0.1902, iDeg: 5.884, omDeg: 251.6, wDeg: 211.4, radiusKm: 0.448, color: '#7d766c', weight: 0.5, facts: [['Sample returned', 'Hayabusa2, 2020-12-06'], ['Shape', 'Spinning-top rubble pile']] },
  { id: 'apophis', name: 'APOPHIS', subtitle: '(99942) APOPHIS — NEAR-EARTH', kind: 'asteroid', aAu: 0.9224, e: 0.1914, iDeg: 3.34, omDeg: 204.0, wDeg: 126.7, radiusKm: 0.185, color: '#d96b52', weight: 0.75, facts: [['2029 approach', '~31 600 km — inside geostationary orbit'], ['Visible to the naked eye', '2029-04-13, from Europe and Africa'], ['Impact risk', 'Ruled out for at least 100 years']] },
  { id: 'phaethon', name: 'PHAETHON', subtitle: '(3200) PHAETHON — NEAR-EARTH', kind: 'asteroid', aAu: 1.2714, e: 0.8898, iDeg: 22.26, omDeg: 265.2, wDeg: 322.2, radiusKm: 2.9, color: '#c2755b', weight: 0.55, facts: [['Source of', 'The Geminid meteor shower'], ['Perihelion', '0.14 AU — closer than Mercury'], ['Behaviour', 'A rock that acts like a comet']] },
  { id: 'itokawa', name: 'ITOKAWA', subtitle: '(25143) ITOKAWA — NEAR-EARTH', kind: 'asteroid', aAu: 1.3241, e: 0.28, iDeg: 1.622, omDeg: 69.1, wDeg: 162.8, radiusKm: 0.165, color: '#8a8175', weight: 0.45, facts: [['Sample returned', 'Hayabusa, 2010-06-13'], ['Length', '535 m']] },
  { id: 'halley', name: "HALLEY'S COMET", subtitle: '1P/HALLEY — PERIODIC COMET', kind: 'comet', aAu: 17.834, e: 0.96714, iDeg: 162.26, omDeg: 58.42, wDeg: 111.33, tp: '1986-02-09T11:00:00Z', radiusKm: 5.5, color: '#86c5d6', weight: 0.85, status: 'OUTBOUND — NEXT PERIHELION 2061', facts: [['Orbit', 'Retrograde — it goes the wrong way round'], ['Period', '~75 years'], ['Next perihelion', '2061-07-28'], ['Meteor showers', 'Eta Aquariids and Orionids']] },
  { id: 'oumuamua', name: "'OUMUAMUA", subtitle: '1I/2017 U1 — INTERSTELLAR OBJECT', kind: 'interstellar', aAu: -1.2793, e: 1.2011, iDeg: 122.74, omDeg: 24.6, wDeg: 241.81, tp: '2017-09-09T14:00:00Z', radiusKm: 0.1, color: '#c084e0', weight: 0.9, status: 'DEPARTED — UNBOUND', facts: [['First confirmed', 'Interstellar object, 2017'], ['Shape', 'Extremely elongated, 6:1 or more'], ['Acceleration', 'Non-gravitational, still unexplained'], ['Now', 'Beyond the orbit of Neptune and leaving']] },
  { id: 'borisov', name: '2I/BORISOV', subtitle: '2I/2019 Q4 — INTERSTELLAR COMET', kind: 'interstellar', aAu: -0.8514, e: 3.3564, iDeg: 44.05, omDeg: 308.15, wDeg: 209.12, tp: '2019-12-08T12:00:00Z', radiusKm: 0.5, color: '#c084e0', weight: 0.85, status: 'DEPARTED — UNBOUND', facts: [['Second confirmed', 'Interstellar object, 2019'], ['Unlike ʻOumuamua', 'Visibly a comet, with a tail'], ['Hyperbolic excess speed', '32 km/s']] },
];

function smallBodyObjects(): SpaceObject[] {
  return SMALL_BODIES.map((b) => {
    const shape = { aAu: b.aAu, e: b.e, iDeg: b.iDeg, omDeg: b.omDeg, wDeg: b.wDeg };
    const phased = b.tp !== undefined;
    const elements = phased ? heliocentric({ ...shape, tp: jdOf(b.tp!) }) : unphased(shape);
    const obj: SpaceObject = {
      id: b.id,
      name: b.name,
      subtitle: b.subtitle,
      kind: b.kind,
      parent: 'sun',
      color: b.color,
      weight: b.weight,
      provenance: phased
        ? P_SMALL_BODY
        : {
            ...P_SMALL_BODY,
            accuracy: 'Orbit shape is published and accurate. Position along the orbit is NOT known offline and is not shown.',
            limitations: 'This build ships the orbit only. The object is placed on it once a live epoch is retrieved from the JPL Small-Body Database.',
          },
      ephemeris: phased ? { kind: 'elements', elements } : { kind: 'elements-unphased', elements },
      tags: ['small-body', b.kind],
      facts: b.facts.map(([label, value]) => ({ label, value })),
    };
    if (b.radiusKm !== undefined) obj.radiusKm = b.radiusKm;
    if (b.status !== undefined) obj.status = b.status;
    if (!phased) obj.phaseUnknown = true;
    return obj;
  });
}

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

export const SUN: SpaceObject = {
  id: 'sun',
  name: 'SUN',
  subtitle: 'G2V — THE LOCAL STAR',
  kind: 'star',
  parent: null,
  radiusKm: RADIUS.sun,
  color: '#ffd07a',
  weight: 1,
  provenance: P_SUN,
  ephemeris: { kind: 'sun' },
  tags: ['star'],
  aliases: ['sol'],
  status: 'MAIN SEQUENCE',
  facts: [
    { label: 'Mass', value: '333 000 × Earth' },
    { label: 'Core temperature', value: '~15.7 million K' },
    { label: 'Age', value: '~4.6 billion years' },
    { label: 'Fuses', value: '600 million tonnes of hydrogen per second' },
  ],
};

/** The full built-in catalogue, in no particular order. */
export function buildCatalog(): SpaceObject[] {
  return [
    SUN,
    ...planetObjects(),
    ...moonObjects(),
    ...probeObjects(),
    ...INNER_MISSIONS,
    ...smallBodyObjects(),
    ...buildSmallBodies(),
    ...buildSpacecraft(),
  ];
}

export { heliocentric as catalogElements, jdOf as catalogJd };
export { wrap2Pi };
