import { AU_KM, RAD } from '../astro/constants';
import { periodDays, type Elements } from '../astro/kepler';
import type { ParticleCloud } from './populations';
import type { SpaceObject } from './types';

/**
 * Turn one member of a simulated population into a selectable object.
 *
 * Built on demand when a belt particle is tapped, rather than held as tens of thousands
 * of catalogue entries. The orbit it reports is genuinely its own — the period, the
 * perihelion, the speed and the inclination all follow from the elements it was generated
 * with, and they obey the same mechanics as everything else on screen. What it is not is
 * a real body, and both the tier badge and the status line say so before anything else.
 */
export function particleObject(cloud: ParticleCloud, index: number): SpaceObject | null {
  const elements: Elements | undefined = cloud.elements[index];
  if (!elements) return null;

  const aAu = elements.a / AU_KM;
  const e = elements.e;
  const period = periodDays(elements);
  const designation = `${cloud.label} ${String(index + 1).padStart(4, '0')}`;

  return {
    id: `sim-${cloud.id}-${index}`,
    name: designation,
    subtitle: 'SIMULATED POPULATION MEMBER',
    kind: 'asteroid',
    parent: 'sun',
    color: cloud.color,
    weight: 0.2,
    provenance: {
      tier: 'simulated',
      source: 'Generated by SPACE RADAR. Not a real object.',
      cadence: 'Regenerated from a fixed seed on every load, so it is the same body each time.',
      accuracy:
        'Not applicable — nothing here corresponds to a catalogued body. The orbital mechanics below are exact for the orbit it was given.',
      limitations: cloud.note,
    },
    ephemeris: { kind: 'elements', elements },
    tags: ['simulated', 'small-body', cloud.id],
    status: 'SIMULATED — NOT A REAL OBJECT',
    facts: [
      { label: 'Population', value: cloud.label },
      { label: 'Semi-major axis', value: `${aAu.toFixed(3)} AU` },
      { label: 'Perihelion', value: `${(aAu * (1 - e)).toFixed(3)} AU` },
      { label: 'Aphelion', value: `${(aAu * (1 + e)).toFixed(3)} AU` },
      { label: 'Eccentricity', value: e.toFixed(4) },
      { label: 'Inclination', value: `${(elements.i * RAD).toFixed(2)}°` },
      {
        label: 'Orbital period',
        value: period ? (period > 700 ? `${(period / 365.25).toFixed(2)} years` : `${period.toFixed(1)} days`) : '—',
      },
      { label: 'Reality check', value: cloud.note },
    ],
  };
}
