import type { Elements, State } from '../astro/kepler';
import type { PlanetId } from '../astro/planets';
import type { Sgp4Satellite } from '../astro/sgp4';
import type { Vec3 } from '../astro/vec';

/**
 * How much to believe a number.
 *
 * Every object in this app carries one of these, and the UI always shows it. The whole
 * point is that you can never mistake a simulated body for a tracked one.
 *
 *  computed  — produced here from a published analytical theory. Deterministic, offline,
 *              valid for any time the scrubber can reach. Planets, the Moon, Lagrange
 *              points.
 *  live      — fetched from an upstream authority this session. Carries a real epoch.
 *  catalog   — published constants baked into the build. Real objects, real numbers, but
 *              frozen at a stated epoch and not refreshed.
 *  simulated — generated by this app. Not a real object. Never presented as one.
 */
export type ProvenanceTier = 'computed' | 'live' | 'catalog' | 'simulated';

export interface Provenance {
  tier: ProvenanceTier;
  /** Who published it, specifically enough to go and check. */
  source: string;
  sourceUrl?: string;
  /** ISO timestamp the data osculates to, when the tier has one. */
  epoch?: string;
  /** How often the upstream changes, in words. */
  cadence: string;
  /** What the error actually is. No hand-waving. */
  accuracy: string;
  /** What this will get wrong, stated plainly. */
  limitations: string;
}

export type ObjectKind =
  | 'star'
  | 'planet'
  | 'dwarf'
  | 'moon'
  | 'spacecraft'
  | 'satellite'
  | 'asteroid'
  | 'comet'
  | 'interstellar'
  | 'lagrange'
  | 'debris';

/** How to place an object at a given instant. */
export type Ephemeris =
  /** The origin of the heliocentric frame. */
  | { kind: 'sun' }
  /** Standish table planet. `earth` resolves to the planet, not the barycentre. */
  | { kind: 'planet'; planet: PlanetId }
  /** Meeus lunar theory, geocentric. */
  | { kind: 'luna' }
  /** Closed or open conic about `parent`. */
  | { kind: 'elements'; elements: Elements }
  /**
   * Conic about `parent` whose phase is not known offline. The path is drawn; the object
   * is not placed until a live epoch arrives.
   */
  | { kind: 'elements-unphased'; elements: Elements }
  /** SGP4 from a two-line element set, about the Earth. */
  | { kind: 'tle'; satellite: Sgp4Satellite }
  /**
   * A body far enough out that the Sun's pull is negligible over the app's time range:
   * a fixed direction from the Sun and a constant radial speed. Used for the interstellar
   * probes, whose published data is exactly this — a distance, a heading and a speed.
   */
  | { kind: 'radiant'; raDeg: number; decDeg: number; auAtEpoch: number; epoch: number; kmPerSec: number }
  /** Sun–Earth Lagrange point, with an optional halo amplitude. */
  | { kind: 'lagrange'; point: 'L1' | 'L2'; haloKm?: number; haloPeriodDays?: number; phase?: number }
  /** A state vector propagated on its own osculating conic about `parent`. */
  | { kind: 'state'; state: State; epoch: number };

export interface Fact {
  label: string;
  value: string;
}

export interface SpaceObject {
  id: string;
  name: string;
  /** Shown under the name: designation, operator, mission. */
  subtitle?: string;
  kind: ObjectKind;
  /** Body this object's ephemeris is referenced to. `null` for the Sun. */
  parent: string | null;
  /** Mean radius, km. Absent for objects too small or too unknown to draw as a disc. */
  radiusKm?: number;
  /** Hex colour for the marker, orbit and label. */
  color: string;
  /**
   * Roughly how interesting this object is, 0–1. Drives label priority and which objects
   * survive at low levels of detail. Not a scientific quantity.
   */
  weight: number;
  provenance: Provenance;
  ephemeris: Ephemeris;
  /** Free-text searchable aliases. */
  aliases?: string[];
  tags: string[];
  facts?: Fact[];
  /** Status line for the object panel, e.g. `ACTIVE`, `CONTACT LOST 2003`. */
  status?: string;
  /** Set when the object is real but its position along the orbit is unknown offline. */
  phaseUnknown?: boolean;
  /**
   * Set when the object IS placed, but its phase along the orbit was not fitted to an
   * ephemeris — the orbit's size, shape and tilt are published, the position on it is a
   * fixed synthetic value. Distinct from `phaseUnknown`, which is not placed at all.
   *
   * Acceptable for a satellite, where the error is bounded by its orbit around its
   * planet. Not acceptable for a heliocentric body, where it would be two orbit radii.
   */
  phaseSynthetic?: boolean;
  /**
   * Radius of this body's sphere of influence about its parent, km — the boundary inside
   * which it, rather than the parent, dominates a small object's motion. This is what the
   * GRAVITY layer draws; it is a defined quantity, r = a·(m/M)^(2/5), not a decoration.
   */
  soiKm?: number;
}

/** An object resolved to a concrete place and time. */
export interface ResolvedObject {
  object: SpaceObject;
  /** Heliocentric position, km, J2000 ecliptic. */
  position: Vec3;
  /** Heliocentric velocity, km/s. */
  velocity: Vec3;
  /** Position relative to `parent`, km. Equal to `position` for heliocentric objects. */
  local: Vec3;
  /** True when the ephemeris could not place it (deep-space TLE, unknown phase, decayed). */
  unplaced: boolean;
}

/** A close approach as published by JPL's CAD service. */
export interface CloseApproach {
  designation: string;
  fullName: string;
  /** Julian Date of closest approach. */
  jd: number;
  /** Miss distance, AU. */
  distAu: number;
  /** Relative velocity, km/s. */
  vRelKmS: number;
  /** Estimated diameter range in metres, when absolute magnitude allows one. */
  diameterM?: [number, number];
  magnitude?: number;
}
