/**
 * Place table for the simulation engine.
 *
 * The coordinates and names are ordinary public geographic facts about Washington State;
 * everything the simulator *generates* on top of them is fictional. `weight` is a rough
 * population/activity weighting so simulated activity lands where people actually are.
 */

export interface SimPlace {
  readonly name: string;
  readonly area: string;
  readonly county: string;
  readonly lat: number;
  readonly lon: number;
  /** Relative likelihood of activity. */
  readonly weight: number;
  /** Approximate radius (km) over which incidents are scattered around the centre. */
  readonly spreadKm: number;
  /** Street names used to synthesise plausible block-level location strings. */
  readonly streets: readonly string[];
}

const COMMON_STREETS = [
  'Main St',
  'Broadway',
  'Park Ave',
  '1st Ave',
  '3rd St',
  'Cedar St',
  'Maple Ln',
  'Riverside Dr',
  'Commerce Way',
  'Industrial Blvd',
];

export const SIM_PLACES: readonly SimPlace[] = [
  {
    name: 'Seattle — Downtown',
    area: 'Seattle',
    county: 'King',
    lat: 47.6062,
    lon: -122.3321,
    weight: 100,
    spreadKm: 2.2,
    streets: ['Pike St', 'Pine St', '3rd Ave', '4th Ave', 'Union St', 'Stewart St', 'Boren Ave'],
  },
  {
    name: 'Seattle — Capitol Hill',
    area: 'Seattle',
    county: 'King',
    lat: 47.6229,
    lon: -122.3212,
    weight: 62,
    spreadKm: 1.6,
    streets: ['E Pine St', 'Broadway E', '12th Ave', 'E Olive Way', 'E Madison St'],
  },
  {
    name: 'Seattle — Ballard',
    area: 'Seattle',
    county: 'King',
    lat: 47.6685,
    lon: -122.3843,
    weight: 44,
    spreadKm: 2,
    streets: ['NW Market St', 'Leary Way NW', '15th Ave NW', 'Shilshole Ave NW'],
  },
  {
    name: 'Seattle — SoDo',
    area: 'Seattle',
    county: 'King',
    lat: 47.5798,
    lon: -122.3345,
    weight: 38,
    spreadKm: 2.4,
    streets: ['1st Ave S', 'Airport Way S', 'S Lander St', 'Occidental Ave S'],
  },
  {
    name: 'Seattle — University District',
    area: 'Seattle',
    county: 'King',
    lat: 47.6587,
    lon: -122.3138,
    weight: 40,
    spreadKm: 1.7,
    streets: ['University Way NE', 'NE 45th St', 'Roosevelt Way NE', 'Brooklyn Ave NE'],
  },
  {
    name: 'Seattle — West Seattle',
    area: 'Seattle',
    county: 'King',
    lat: 47.5622,
    lon: -122.386,
    weight: 36,
    spreadKm: 3,
    streets: ['California Ave SW', 'SW Alaska St', 'Fauntleroy Way SW', 'Delridge Way SW'],
  },
  {
    name: 'Bellevue',
    area: 'Bellevue',
    county: 'King',
    lat: 47.6101,
    lon: -122.2015,
    weight: 55,
    spreadKm: 3.5,
    streets: ['NE 8th St', 'Bellevue Way NE', '116th Ave NE', 'Main St', '148th Ave SE'],
  },
  {
    name: 'Redmond',
    area: 'Redmond',
    county: 'King',
    lat: 47.674,
    lon: -122.1215,
    weight: 32,
    spreadKm: 3,
    streets: ['Redmond Way', 'Avondale Rd NE', 'NE 40th St', 'Cleveland St'],
  },
  {
    name: 'Kirkland',
    area: 'Kirkland',
    county: 'King',
    lat: 47.6769,
    lon: -122.2059,
    weight: 30,
    spreadKm: 2.8,
    streets: ['Lake St S', 'Central Way', '124th Ave NE', 'Market St'],
  },
  {
    name: 'Renton',
    area: 'Renton',
    county: 'King',
    lat: 47.4829,
    lon: -122.2171,
    weight: 38,
    spreadKm: 3.4,
    streets: ['Rainier Ave S', 'S Grady Way', 'SW Sunset Blvd', 'NE 4th St'],
  },
  {
    name: 'Kent',
    area: 'Kent',
    county: 'King',
    lat: 47.3809,
    lon: -122.2348,
    weight: 36,
    spreadKm: 3.6,
    streets: ['Central Ave N', 'W Meeker St', 'Kent-Des Moines Rd', '104th Ave SE'],
  },
  {
    name: 'Federal Way',
    area: 'Federal Way',
    county: 'King',
    lat: 47.3223,
    lon: -122.3126,
    weight: 30,
    spreadKm: 3.2,
    streets: ['Pacific Hwy S', 'S 320th St', '1st Ave S', 'SW Campus Dr'],
  },
  {
    name: 'Auburn',
    area: 'Auburn',
    county: 'King',
    lat: 47.3073,
    lon: -122.2285,
    weight: 24,
    spreadKm: 3,
    streets: ['Auburn Way N', 'A St SE', 'W Main St', 'Lakeland Hills Way SE'],
  },
  {
    name: 'Tacoma — Downtown',
    area: 'Tacoma',
    county: 'Pierce',
    lat: 47.2529,
    lon: -122.4443,
    weight: 62,
    spreadKm: 2.4,
    streets: ['Pacific Ave', 'Broadway', 'S 11th St', 'Market St', 'Tacoma Ave S'],
  },
  {
    name: 'Tacoma — Hilltop',
    area: 'Tacoma',
    county: 'Pierce',
    lat: 47.2506,
    lon: -122.4614,
    weight: 34,
    spreadKm: 1.8,
    streets: ['MLK Jr Way', 'S 19th St', 'S Yakima Ave', 'S Sprague Ave'],
  },
  {
    name: 'Lakewood',
    area: 'Lakewood',
    county: 'Pierce',
    lat: 47.1718,
    lon: -122.5185,
    weight: 26,
    spreadKm: 3.2,
    streets: ['Bridgeport Way SW', 'Steilacoom Blvd SW', 'Pacific Hwy SW', '100th St SW'],
  },
  {
    name: 'Puyallup',
    area: 'Puyallup',
    county: 'Pierce',
    lat: 47.1854,
    lon: -122.2929,
    weight: 22,
    spreadKm: 3,
    streets: ['Meridian St', 'River Rd', '9th St SW', 'Shaw Rd E'],
  },
  {
    name: 'Everett',
    area: 'Everett',
    county: 'Snohomish',
    lat: 47.9789,
    lon: -122.2021,
    weight: 42,
    spreadKm: 3.2,
    streets: ['Broadway', 'Evergreen Way', 'Colby Ave', 'Hewitt Ave', '41st St'],
  },
  {
    name: 'Lynnwood',
    area: 'Lynnwood',
    county: 'Snohomish',
    lat: 47.8279,
    lon: -122.3051,
    weight: 26,
    spreadKm: 2.8,
    streets: ['196th St SW', 'Highway 99', '44th Ave W', 'Alderwood Mall Pkwy'],
  },
  {
    name: 'Marysville',
    area: 'Marysville',
    county: 'Snohomish',
    lat: 48.0518,
    lon: -122.1771,
    weight: 18,
    spreadKm: 3,
    streets: ['State Ave', '4th St', 'Grove St', '88th St NE'],
  },
  {
    name: 'Spokane — Downtown',
    area: 'Spokane',
    county: 'Spokane',
    lat: 47.6588,
    lon: -117.426,
    weight: 58,
    spreadKm: 2.6,
    streets: ['W Riverside Ave', 'N Division St', 'W Sprague Ave', 'N Monroe St'],
  },
  {
    name: 'Spokane Valley',
    area: 'Spokane Valley',
    county: 'Spokane',
    lat: 47.6733,
    lon: -117.2394,
    weight: 28,
    spreadKm: 3.6,
    streets: ['E Sprague Ave', 'N Pines Rd', 'E Broadway Ave', 'N Sullivan Rd'],
  },
  {
    name: 'Vancouver',
    area: 'Vancouver',
    county: 'Clark',
    lat: 45.6387,
    lon: -122.6615,
    weight: 44,
    spreadKm: 3.8,
    streets: ['Main St', 'Mill Plain Blvd', 'Fourth Plain Blvd', 'NE Andresen Rd'],
  },
  {
    name: 'Olympia',
    area: 'Olympia',
    county: 'Thurston',
    lat: 47.0379,
    lon: -122.9007,
    weight: 26,
    spreadKm: 2.6,
    streets: ['Capitol Way S', '4th Ave E', 'Martin Way E', 'Harrison Ave NW'],
  },
  {
    name: 'Lacey',
    area: 'Lacey',
    county: 'Thurston',
    lat: 47.0343,
    lon: -122.8232,
    weight: 16,
    spreadKm: 2.6,
    streets: ['Martin Way E', 'Sleater Kinney Rd SE', 'College St SE', 'Pacific Ave SE'],
  },
  {
    name: 'Bellingham',
    area: 'Bellingham',
    county: 'Whatcom',
    lat: 48.7519,
    lon: -122.4787,
    weight: 26,
    spreadKm: 2.8,
    streets: ['N State St', 'Cornwall Ave', 'Holly St', 'Lakeway Dr', 'Meridian St'],
  },
  {
    name: 'Yakima',
    area: 'Yakima',
    county: 'Yakima',
    lat: 46.6021,
    lon: -120.5059,
    weight: 24,
    spreadKm: 3,
    streets: ['N 1st St', 'Yakima Ave', 'S 16th Ave', 'Nob Hill Blvd'],
  },
  {
    name: 'Kennewick',
    area: 'Kennewick',
    county: 'Benton',
    lat: 46.2112,
    lon: -119.1372,
    weight: 20,
    spreadKm: 3,
    streets: ['W Clearwater Ave', 'N Edison St', 'W Canal Dr', 'S Olympia St'],
  },
  {
    name: 'Richland',
    area: 'Richland',
    county: 'Benton',
    lat: 46.2857,
    lon: -119.2845,
    weight: 14,
    spreadKm: 2.8,
    streets: ['George Washington Way', 'Jadwin Ave', 'Swift Blvd', 'Columbia Point Dr'],
  },
  {
    name: 'Pasco',
    area: 'Pasco',
    county: 'Franklin',
    lat: 46.2396,
    lon: -119.1006,
    weight: 14,
    spreadKm: 2.8,
    streets: ['W Lewis St', 'N 4th Ave', 'Court St', 'Road 68'],
  },
  {
    name: 'Wenatchee',
    area: 'Wenatchee',
    county: 'Chelan',
    lat: 47.4235,
    lon: -120.3103,
    weight: 12,
    spreadKm: 2.4,
    streets: ['N Wenatchee Ave', 'S Mission St', 'Orondo Ave', 'Miller St'],
  },
  {
    name: 'Bremerton',
    area: 'Bremerton',
    county: 'Kitsap',
    lat: 47.5673,
    lon: -122.6329,
    weight: 18,
    spreadKm: 2.6,
    streets: ['Kitsap Way', 'Burwell St', 'Wheaton Way', 'Callow Ave'],
  },
  {
    name: 'Silverdale',
    area: 'Silverdale',
    county: 'Kitsap',
    lat: 47.6445,
    lon: -122.6949,
    weight: 10,
    spreadKm: 2.4,
    streets: ['Silverdale Way NW', 'NW Bucklin Hill Rd', 'Ridgetop Blvd NW'],
  },
  {
    name: 'Mount Vernon',
    area: 'Mount Vernon',
    county: 'Skagit',
    lat: 48.4212,
    lon: -122.334,
    weight: 12,
    spreadKm: 2.4,
    streets: ['Riverside Dr', 'College Way', 'S 1st St', 'Freeway Dr'],
  },
  {
    name: 'Ellensburg',
    area: 'Ellensburg',
    county: 'Kittitas',
    lat: 46.9965,
    lon: -120.5478,
    weight: 8,
    spreadKm: 2,
    streets: ['N Main St', 'W University Way', 'Canyon Rd', 'E 8th Ave'],
  },
  {
    name: 'Walla Walla',
    area: 'Walla Walla',
    county: 'Walla Walla',
    lat: 46.0646,
    lon: -118.343,
    weight: 10,
    spreadKm: 2.2,
    streets: ['E Main St', 'S 2nd Ave', 'Isaacs Ave', 'Rose St'],
  },
  {
    name: 'Moses Lake',
    area: 'Moses Lake',
    county: 'Grant',
    lat: 47.1301,
    lon: -119.2781,
    weight: 9,
    spreadKm: 2.6,
    streets: ['W Broadway Ave', 'S Pioneer Way', 'Stratford Rd', 'Valley Rd'],
  },
  {
    name: 'Port Angeles',
    area: 'Port Angeles',
    county: 'Clallam',
    lat: 48.1181,
    lon: -123.4307,
    weight: 8,
    spreadKm: 2.2,
    streets: ['E Front St', 'Lincoln St', 'W 8th St', 'Race St'],
  },
  {
    name: 'Aberdeen',
    area: 'Aberdeen',
    county: 'Grays Harbor',
    lat: 46.9754,
    lon: -123.8157,
    weight: 8,
    spreadKm: 2.2,
    streets: ['E Wishkah St', 'S Boone St', 'W Market St', 'Simpson Ave'],
  },
  {
    name: 'Longview',
    area: 'Longview',
    county: 'Cowlitz',
    lat: 46.1382,
    lon: -122.9382,
    weight: 10,
    spreadKm: 2.4,
    streets: ['Ocean Beach Hwy', 'Commerce Ave', '15th Ave', 'Washington Way'],
  },
  {
    name: 'Pullman',
    area: 'Pullman',
    county: 'Whitman',
    lat: 46.7298,
    lon: -117.1817,
    weight: 8,
    spreadKm: 1.8,
    streets: ['NE Stadium Way', 'S Grand Ave', 'E Main St', 'NW Terre View Dr'],
  },
  {
    name: 'Tri-Cities Corridor — I-182',
    area: 'Benton County',
    county: 'Benton',
    lat: 46.2652,
    lon: -119.2001,
    weight: 6,
    spreadKm: 6,
    streets: ['I-182', 'SR-240', 'Queensgate Dr'],
  },
  {
    name: 'I-5 Corridor — Joint Base Vicinity',
    area: 'Pierce County',
    county: 'Pierce',
    lat: 47.1067,
    lon: -122.5867,
    weight: 8,
    spreadKm: 7,
    streets: ['I-5', 'Mounts Rd', 'Steilacoom-DuPont Rd'],
  },
  {
    name: 'US-2 Corridor — Stevens Pass Approach',
    area: 'King County',
    county: 'King',
    lat: 47.7896,
    lon: -121.5527,
    weight: 5,
    spreadKm: 9,
    streets: ['US-2', 'Index-Galena Rd', 'Old Cascade Hwy'],
  },
  {
    name: 'I-90 Corridor — Snoqualmie Pass',
    area: 'Kittitas County',
    county: 'Kittitas',
    lat: 47.3923,
    lon: -121.4003,
    weight: 6,
    spreadKm: 10,
    streets: ['I-90', 'Gold Creek Rd', 'Hyak Dr E'],
  },
  {
    name: 'Olympic Peninsula — US-101',
    area: 'Jefferson County',
    county: 'Jefferson',
    lat: 47.8107,
    lon: -122.8484,
    weight: 4,
    spreadKm: 12,
    streets: ['US-101', 'Center Rd', 'Paradise Bay Rd'],
  },
];

export function streetsFor(place: SimPlace): readonly string[] {
  return place.streets.length > 0 ? place.streets : COMMON_STREETS;
}

/** Totals used by the weighted picker. */
export const TOTAL_PLACE_WEIGHT = SIM_PLACES.reduce((sum, p) => sum + p.weight, 0);
